#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh &

bspc config border_width            2
bspc config window_gap              8
bspc config bottom_padding          25

bspc config normal_border_color     '#373E4D'
bspc config active_border_color     '#373E4D'
bspc config focused_border_color    '#96B5B4'
#4c5356
bspc config presel_feedback_color   '#2b3135'
#bspc config normal_frame_opacity    0.0
#bspc config focused_frame_opacity   0.1

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_by_distance       true
bspc config history_aware_focus     true

bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9
# I II III IV V VI VII VIII
#bspc monitor DVI-I-1 -s HDMI-0

# rules
bspc rule -a Firefox desktop=^1
bspc rule -a Spotify desktop=^2
bspc rule -a Deluge-gtk desktop=^3

# launch progams
#firefox &
#spotify &
#deluge-gtk
