#! /bin/sh

sxhkd &
compton &
$HOME/.config/polybar/launch.sh &

bspc config border_width            2
bspc config window_gap              8
bspc config bottom_padding          25

bspc config normal_border_color     '#373E4D'
bspc config active_border_color     '#373E4D'
bspc config focused_border_color    '#96B5B4'
#4c5356
bspc config presel_feedback_color   '#2b3135'
#bspc config normal_frame_opacity    0.0
#bspc config focused_frame_opacity   0.1

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
# bspc config focus_by_distance       true
# bspc config history_aware_focus     true

bspc config ignore_ewmh_focus	    true

bspc config pointer_modifier lock
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action1 resize_corner

bspc monitor HDMI-0 -n right
bspc monitor DVI-I-1 -n left
bspc monitor right -d 1 2 3 4
bspc monitor left -d 5 6 7 8

# rules
bspc rule -a google-chrome-stable desktop=1
bspc rule -a spotify desktop=2
bspc rule -a deluge desktop=3
bspc rule -a atom state=tiled desktop=4
bspc rule -a discord desktop=5

# launch progams
exec google-chrome-stable &
exec spotify &
exec deluge &
exec atom &
exec discord
